---
- name: Create Terraform Folder
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}/terraform'
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}/roles/terraform'
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}/roles/terraform/tasks'
