---
- name: Create Folders
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ op_folder_location }}'
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}'
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}/inventory'
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}/files'
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}/keys'
  - '{{ op_folder_location }}/{{ warhorse.general.op_number }}/terraform'

- name: Create Folders
  file:
    path: '{{ op_folder_location }}/{{ warhorse.general.op_number }}/files/{{ item.name }}'
    state: directory
  with_items:
  - '{{ warhorse.vm }}'
