---
- ansible.builtin.include_tasks: folders.yml
- ansible.builtin.include_tasks: ssh.yml
- ansible.builtin.include_tasks: inventory.yml
- ansible.builtin.include_tasks: generate.yml
- ansible.builtin.include_tasks: deployment.yml
- ansible.builtin.include_tasks: nginx.yml
  with_items: "{{ warhorse.vm }}"
  when: item.nginx.config_file is not defined and item.http_proxy == "nginx"
- ansible.builtin.include_tasks: evilginx2.yml
  with_items: "{{ warhorse.vm }}"
  when: item.evilginx2 is defined
- ansible.builtin.include_tasks: cobaltstrike.yml
  with_items: "{{ warhorse.vm }}"
  when: item.cobaltstrike is defined
