---
- name: Create SSH Keys
  community.crypto.openssh_keypair:
    path: "./OP/{{ warhorse.general.op_number }}/keys/id_rsa_ansible_{{ warhorse.general.op_number }}"
    size: 521
    type: "ed25519"
